### PR TITLE
Product page update

### PR DESCRIPTION
**Pull request by cafemoloko**
Product photos added.

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
So I'm not sure if this is a preview issue.  But I'm seeing API and GUI misaligned here:

image

**Comment by Luxonis-Brandon** [comment]
The product pages look good.  But could you please update the product pages to use Gen1 for setup/testing @cafemoloko ?

image

**Comment by cafemoloko** [comment]
> So I'm not sure if this is a preview issue. But I'm seeing API and GUI misaligned here:

oh, it doesn't look good. I'll fix it.

>The product pages look good. But could you please update the product pages to use Gen1 for setup/testing 

Gen1?

**Comment by Luxonis-Brandon** [comment]
Oh sorry @cafemoloko I meant to write: Update the product pages to show Gen2 instead of what is currently on there, which is Gen1.

**Review by VanDavv — CHANGES_REQUESTED** [review]
The product-related changes looks good at a first glance, but there are also changes unrelated to this PR

**Pull request closed without merging**
