### PR TITLE
Add Github Workflow to run install script

### PR DESCRIPTION
**Pull request by pamolloy**

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Oh cool.  Not familiar with these, but sounds useful!

**Comment by VanDavv** [comment]
@pamolloy I wonder - why it didn't run on your commit? I don't see any runs in Actions tab

**Comment by themarpe** [comment]
@VanDavv I think the workflow didn't run because of wrong folder name `worksflows` instead of `workflows`

**Comment by VanDavv** [comment]
Yes, that helped @themarpe , I changed it quickly and the workflow ran (and failed unfortunately)

```
The workflow is not valid. .github/workflows/test-install-dependencies.yml (Line: 11, Col: 9): Unexpected value 'source/_static/install_dependencies.sh'
```

**Comment by szabi-luxonis** [comment]
Can you add CI for windows too? @pamolloy

**Comment by pamolloy** [comment]
@szabi-luxonis Definitely, I didn't add it because the https://docs.luxonis.com/en/latest/pages/api/#windows documentation doesn't recommend using the `bat` file. Is that `bat` file used anywhere? Or is there something else worth testing on Windows?

**Comment by pamolloy** [comment]
I'm going to remove macOS job after trying to debug with @alex-luxonis. I've created issue #113 to keep track of it and hopefully revisit it later.

**Pull request merged**
