### PR TITLE
Added some additional info for the PoE devices

### PR DESCRIPTION
**Pull request by Erol444**

### CODE REVIEW

**Comment by themarpe** [comment]
The GIF seems to have its aspect ratio changed (too slim)
image

+ the gif is ~17MiB, try reducing it a bit, to load faster

**Comment by Luxonis-Brandon** [comment]
Agreed on the aspect ratio on the GIF.

Also to reduce the size of the GIF, I think we can trim off the front of the video and the end of the video, to only really show just initially holding it, going directly to plugging in, and then once it starts blinking cut there, or shortly after where it "feels right".

Not sure if there are other ways (other than temporal) to make the GIF smaller as well?  @VanDavv has a GIF tool he likes.

**Comment by VanDavv** [comment]
I use https://ezgif.com/ for all my gif works and it's great

**Review by VanDavv — COMMENTED** [review]
Following @Luxonis-Brandon mention, I'd suggest using ezgif to limit the size of the gif and then maybe even hosting it on GitHub (has to be 10MB or (preferably) less)

**Comment by Erol444** [comment]
Thanks Lukasz for the app, wasn't aware of it, it's great! Resized gif to 50%, it's less than 10MB now so it can be hosted on github as well
poe-connected

**Review by VanDavv — APPROVED** [review]

**Comment by cafemoloko** [comment]
Thanks, @Erol444. I've linked this guide to hardware docs, too (OAK-1-POE and OAK-D-POE).

**Pull request merged**
