### PR TITLE
Add neural networks performance table and gen2 demo script

### PR DESCRIPTION
**Pull request by VanDavv**
This PR adds neural networks performance table, showing how fast can nn's run on DepthAI.

To measure the performance, I've created a kickoff of [gen2 demo script in depthai repository](https://github.com/luxonis/depthai/blob/gen2/gen2_demo.py), which already handles mobilenet-based and yolo-based networks, and utilizes model downloader to compile blobs. More features can be migrated soon, the current state was enough to produce this table (which surely can be extend further)

It look like this now

Screenshot_2021-02-23_11-09-59

### CODE REVIEW

**Review by szabi-luxonis — CHANGES_REQUESTED** [review]
Most of the models capped at 30 fps are limited by the camera FPS, mobilenet ssd for example can run at 40fps,so does tiny yolo v3

**Comment by VanDavv** [comment]
Yes, good catch, will make it independent, thanks!

**Comment by szabi-luxonis** [comment]
> This PR adds neural networks performance table, showing how fast can nn's run on DepthAI.
> 
> To measure the performance, I've created a kickoff of [gen2 demo script in depthai repository](https://github.com/luxonis/depthai/blob/gen2/gen2_demo.py), which already handles mobilenet-based and yolo-based networks, and utilizes model downloader to compile blobs. More features can be migrated soon, the current state was enough to produce this table (which surely can be extend further)
> 
> It look like this now
> 
> Screenshot_2021-02-23_11-09-59

Did you use openvino 2021.1 or 2021.2 ? It's worth mentioning the context when taking measurements since the performance will likely drop based on system load. E.g. only X camera running at Y fps, resolution, models compiled with openvino XY for 6 shaves, 2 inference threads. (best performance)

**Comment by Luxonis-Brandon** [comment]
Yes, agreed.  We should manually set the framerate of the cameras to max out the neural performance.  Which is to say, set the camera FPS just below what the max neural inference FPS can be, which will maximize the framerate and show users how to do so as well.

**Comment by BryanChrisBrown** [comment]
Is there any kind of “task manager” view for the movidius chip? While the FPS metrics are good for individual neural nets I’m interested in seeing how much of the movidius chip’s actual bandwidth/compute they use. For example “generic neural net uses X% of available compute at 30fps”. This would be beneficial for those who want to run multiple neural nets simultaneously, like feature detection and people detection.

**Comment by Luxonis-Brandon** [comment]
Yes, I think @szabi-luxonis recently implemented some monitoring like this including CMX usage, DDR usage, etc.  Having to hop on a call otherwise I'd look it up now.

**Comment by szabi-luxonis** [comment]
> Is there any kind of “task manager” view for the movidius chip? While the FPS metrics are good for individual neural nets I’m interested in seeing how much of the movidius chip’s actual bandwidth/compute they use. For example “generic neural net uses X% of available compute at 30fps”. This would be beneficial for those who want to run multiple neural nets simultaneously, like feature detection and people detection.

You can set log level to info to get data how resources are allocated, CPU temperature, load, memory usage.
set environment variable: `export DEPTHAI_LEVEL=info` 
Alternatively you can access them programatically, here is an example:
https://github.com/luxonis/depthai-core/blob/gen2_develop/examples/src/system_information_example.cpp

**Comment by VanDavv** [comment]
Closing in favor of https://github.com/luxonis/depthai-docs-website/pull/231

**Pull request closed without merging**
