### PR TITLE
Replace /etc/lsb-release with /etc/os-release

### PR DESCRIPTION
**Pull request by pamolloy**
And print errors when the distribution or host are not identified.

See the following for more information on /etc/os-release:
- https://stackoverflow.com/questions/47838800/
- http://0pointer.de/blog/projects/os-release.html

### CODE REVIEW

**Comment by pamolloy** [comment]
I tested this quickly in a Ubuntu container (which required installing `sudo`).

**Comment by themarpe** [comment]
If os-release covers lsb-release cases as well then LGTM
CC: @VanDavv

**Comment by pamolloy** [comment]
I'll wait until #109 is merged and rebase on top of @alex-luxonis's changes.

**Review by VanDavv — APPROVED** [review]
LGTM

**Pull request merged**
