### PR TITLE
oak-d as a video device

### PR DESCRIPTION
**Pull request by cafemoloko**
Added _How to run OAK-D as video device_ to the FAQ.

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks this looks good.  It would be good to set a reminder to update in say a month (can do in slack) as I think with the DDR boot improvements, this could get easier/cleaner (and mainlined).

So on the DDR-boot @themarpe / @alex-luxonis - am I right in assuming that that can make UVC nodes easier/cleaner?

**Comment by themarpe** [comment]
Correct, no need for separate branch, etc...
I'd wait as well

**Comment by cafemoloko** [comment]
@Luxonis-Brandon I set reminded on Slack. @themarpe - so this one can be merged now and updated later?

**Comment by themarpe** [comment]
@cafemoloko I think we can, we'll update later

**Comment by Luxonis-Brandon** [comment]
Oh also @cafemoloko when you get a second could you also link to this new section from [here](https://docs.luxonis.com/en/latest/pages/faq/#is-it-possible-to-use-the-rgb-camera-and-or-the-stereo-pair-as-a-regular-uvc-camera) if you haven't already?   Also as good practice we should search the FAQ for any relevant sections/etc. just with a simple ctrl-f (e.g. in this case for UVC) to update other FAQ entries if/as necessary.  (And sorry if you already did this and I missed it.).

**Pull request merged**
