### PR TITLE
Change index page and create DepthAI Ecosystem page

### PR DESCRIPTION
**Pull request by VanDavv**
Preview available here - https://luxonis-docs-website--174.com.readthedocs.build/en/174/

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Question on this:

image

Is there a way to make the sections of the page be subsections on the left there?  I think would be more compelling when you click/scroll.  Thoughts?

**Comment by cafemoloko** [comment]
Answering your question @Luxonis-Brandon: yes, it is possible. 
@VanDavv is it a new landing page? If so, would you consider adding an installation guide first (or I can do that)?

**Comment by Luxonis-Brandon** [comment]
Thanks!

**Comment by VanDavv** [comment]
@cafemoloko @Luxonis-Brandon 

> Is there a way to make the sections of the page be subsections on the left there?

I added a new ToC with its contents. This is a bit bugged in sphinx ATM, but I created a custom workaround so that this TOC renders correctly. Sphinx treats this kind of reference as self-reference and raises warnings
```
WARNING: self-referenced toctree found. Ignored.
WARNING: circular toctree references detected, ignoring: index <- index
```

and the main reason why it doesn't work is that it takes `.. toctree::` directives also into account, so below `Ecosystem` header it has loaded all listed ToCs as child items (so they were duplicated and incorrectly nested)

Related issue: https://github.com/sphinx-doc/sphinx/issues/2103

> would you consider adding an installation guide first 

Wouldn't Gen2 demo installation instructions (shown on the landing page in demo script) solve this?
It should install everything needed for most of the cases, also has a check for udev rules [here](https://github.com/luxonis/depthai/blob/369c189edcb7609fc2dabc4a7d5b4534ef756465/depthai_helpers/config_manager.py#L155).
For sure it would require improvements to handle some cases (or point to install instructions in API section), but as a quick start it suits well I think.
Thoughts?

**Comment by cafemoloko** [comment]
> > would you consider adding an installation guide first
> 
> Wouldn't Gen2 demo installation instructions (shown on the landing page in demo script) solve this?
> It should install everything needed for most of the cases, also has a check for udev rules [here](https://github.com/luxonis/depthai/blob/369c189edcb7609fc2dabc4a7d5b4534ef756465/depthai_helpers/config_manager.py#L155).
> For sure it would require improvements to handle some cases (or point to install instructions in API section), but as a quick start it suits well I think.
> Thoughts?

@VanDavv 
If I wanted to run the device for the first time, I would look for well-known keywords in the documentation.
I see that you added `New to DepthAI? Start here`, that takes to `Demo script` few lines down. Cool. What I really miss here is clear instruction on how to start. **Something eye-catching :)**

 _To start with / run DetphAI, type the following commands in the terminal._ 

or

_To start with DepthAI, clone the github repo, run the command that installs all dependencies, and then run the demo._

```
git clone git@github.com:luxonis/depthai.git
cd depthai
git checkout gen2
python3 install_requirements.py
python3 depthai_demo.py
```
I hope you see my point here :)

**Comment by VanDavv** [comment]
Thanks, @cafemoloko, yes, that makes sense. And FWIW this association-based thinking is one of the reasons we picked RTD - because many people know its layout and are familiar with it.

I'll merge this PR, not to hold next updates, but we can iterate this page further

**Pull request merged**
