### PR TITLE
Briefing

### PR DESCRIPTION
**Pull request by realWadim**

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
Thanks @realWadim .  So on our old docs system we could see a preview of the docs site based on a PR.

Do you know if there is a way to do that with ReadTheDocs?

IF it's something you could make happen, that would be super useful for reviewing things like this.  Or perhaps is it already possible and I just don't know?

**Comment by realWadim** [comment]
Preview:
https://docs.luxonis.com/en/briefing/

**Review by Luxonis-Brandon — APPROVED** [review]
Thanks.  That looks great to me.  I think we should merge it.  And for the record, does the preview always work like that based on the branch name?

**Comment by VanDavv** [comment]
@Luxonis-Brandon It is easy to do, but has to be done manually on RTD site

**Comment by Luxonis-Brandon** [comment]
Thanks.  Do they have some sort of automated way to make this happen when a PR is made?  Taht would be SUPER helpful.

Thoughts?

Thanks,
Brandon

**Comment by VanDavv** [comment]
@Luxonis-Brandon I've sent an email to RTD support regarding this feature, will enable if possible and circle back

**Comment by Luxonis-Brandon** [comment]
Thanks!

**Comment by VanDavv** [comment]
@Luxonis-Brandon RTD support reached back and pointed us to https://docs.readthedocs.io/en/stable/automation-rules.html - I've asked @realWadim to help with automating the releases on branches

**Comment by Luxonis-Brandon** [comment]
Thanks.  So is it possible to do automating only on PR instead of branch?

**Comment by VanDavv** [comment]
No, they only support releases on tags and branches. I've been discussing this topic today with @realWadim and I guess we'll just as a rule on tags, so you can tag your commit e.g. `deploy_briefing` and it will create a release automatically (because we supply a regexp in RTD to check if it should deploy a certain tag, in this case it would contain `^deploy_.*` expression and automatically deploy every tag matching)

**Comment by Luxonis-Brandon** [comment]
Oh cool that would be great I think and good enough so that PR auto-deployment isn't needed.

**Pull request merged**
